# Generated by Django 6.0.4 on 2026-04-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
