# Generated by Django 6.0.4 on 2026-04-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ENT', 'Entrada (Receita)'), ('SAI', 'Saída (Despesa)')], max_length=3)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DIN', 'Dinheiro'), ('CRT', 'Cartão de Crédito/Débito'), ('PIX', 'PIX'), ('BOL', 'Boleto')], max_length=3, null=True)),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financeiro', to='servicos.ordemservico')),
            ],
        ),
    ]
