# Generated by Django 6.0.4 on 2026-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecas',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='pecas',
            old_name='estoque',
            new_name='estoque_atual',
        ),
        migrations.AlterField(
            model_name='itempeca',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
