# Generated by Django 6.0.4 on 2026-04-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_nome_pecas_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempeca',
            name='os',
        ),
        migrations.AddField(
            model_name='itempeca',
            name='ordem_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pecas', to='servicos.ordemservico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempeca',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempeca',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
