# Generated by Django 6.0.4 on 2026-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_remove_itempeca_os_itempeca_ordem_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempeca',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pecas',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pecas',
            name='estoque_atual',
            field=models.IntegerField(default=0, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='pecas',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Mão de Obra'),
        ),
    ]
