# Generated by Django 6.0.4 on 2026-04-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_itempeca_preco_unitario_alter_pecas_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pecas',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='total',
            new_name='valor_total',
        ),
        migrations.AlterField(
            model_name='itempeca',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempeca',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servicos', to='servicos.ordemservico'),
        ),
        migrations.AlterField(
            model_name='itemservico',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ORC', 'Orçamento'), ('APR', 'Aprovado'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='ORC', max_length=3),
        ),
        migrations.AlterField(
            model_name='pecas',
            name='estoque_atual',
            field=models.IntegerField(default=0, verbose_name='Stock Atual'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mão de Obra'),
        ),
    ]
