# Generated by Django 6.0.4 on 2026-04-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_alter_pecas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
