# Generated by Django 6.0.4 on 2026-04-21 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_pecas_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo_produto', models.CharField(choices=[('PA', 'Produto Acabado'), ('MP', 'Matéria Prima'), ('SV', 'Serviço'), ('MC', 'Material Consumo'), ('PI', 'Produto Intermediário')], default='PA', max_length=2, verbose_name='Tipo de Produto')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('JG', 'Jogo'), ('MI', 'Milheiro'), ('M', 'Metros'), ('KG', 'Quilograma')], default='UN', max_length=2, verbose_name='Unidade de Medida')),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Compra')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.RemoveField(
            model_name='itemservico',
            name='os',
        ),
        migrations.RemoveField(
            model_name='itemservico',
            name='servico',
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_os', to='servicos.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPeca',
        ),
        migrations.DeleteModel(
            name='Pecas',
        ),
        migrations.DeleteModel(
            name='ItemServico',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
