# Generated by Django 6.0.4 on 2026-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_produto_remove_itemservico_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ORC', 'Orçamento'), ('APR', 'Aprovada'), ('PRO', 'Em Processo'), ('FIN', 'Finalizada'), ('CAN', 'Cancelada')], default='ORC', max_length=3),
        ),
    ]
